# Generated by Django 5.1.2 on 2025-06-23 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamSubmission',
        ),
    ]
