# Generated by Django 5.1.2 on 2025-10-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_delete_examsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exam_questions/'),
        ),
    ]
