# Generated by Django 5.1.2 on 2025-11-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_examquestion_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='time_taken',
            field=models.DurationField(blank=True, help_text='Total time taken by the student', null=True),
        ),
    ]
