# Generated by Django 5.2.1 on 2025-12-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_alter_section_name'),
        ('exam', '0004_examresult_time_taken'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduledexam',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='scheduledexam',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'completed'), _negated=True), fields=('exam', 'college', 'course', 'semester', 'year'), name='unique_active_schedule'),
        ),
    ]
