# Generated by Django 5.2.1 on 2025-12-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_alter_section_name'),
        ('exam', '0005_alter_scheduledexam_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scheduledexam',
            name='unique_active_schedule',
        ),
        migrations.AlterField(
            model_name='scheduledexam',
            name='status',
            field=models.CharField(choices=[('started', 'started'), ('completed', 'completed'), ('pending', 'pending')], default='pending', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='scheduledexam',
            unique_together={('exam', 'college', 'course', 'semester', 'year')},
        ),
    ]
