# Generated by Django 5.2.1 on 2025-12-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_remove_scheduledexam_unique_active_schedule_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledexam',
            options={'ordering': ['-start_datetime']},
        ),
        migrations.AlterUniqueTogether(
            name='scheduledexam',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='scheduledexam',
            name='status',
            field=models.CharField(choices=[('started', 'started'), ('completed', 'completed'), ('pending', 'pending')], max_length=15),
        ),
    ]
