# Generated by Django 5.2.1 on 2025-12-03 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_alter_scheduledexam_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='scheduled_exam',
            field=models.ForeignKey(blank=True, help_text='The specific scheduled exam instance', null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.scheduledexam'),
        ),
    ]
