# Generated by Django 5.2.1 on 2025-12-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_remove_scheduledexam_result_released_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledexam',
            name='section',
        ),
        migrations.AddField(
            model_name='scheduledexam',
            name='result_released',
            field=models.BooleanField(default=False, help_text='If true, students can view results immediately after submission.'),
        ),
    ]
