# Generated by Django 5.2.1 on 2026-03-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_remove_scheduledexam_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledexam',
            name='require_attendance',
            field=models.BooleanField(default=False, help_text='Allow exam only for students marked Present in training attendance.'),
        ),
    ]
