# Generated by Django 5.2.1 on 2026-03-09 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_alter_section_name'),
        ('exam', '0012_scheduledexam_require_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledexam',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college.section'),
        ),
    ]
