# Generated by Django 5.2.1 on 2026-03-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_scheduledexam_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledexam',
            name='section',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
