# Generated by Django 5.0.14 on 2026-03-31 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0014_alter_scheduledexam_section"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="examresult",
            name="allow_retake",
            field=models.BooleanField(
                default=False, help_text="If True, student can retake the exam"
            ),
        ),
        migrations.AddField(
            model_name="examresult",
            name="is_monitored",
            field=models.BooleanField(
                default=False,
                help_text="True if admin is monitoring this student's exam",
            ),
        ),
        migrations.AddField(
            model_name="examresult",
            name="is_retaken_result",
            field=models.BooleanField(
                default=False, help_text="True if this is a retake result"
            ),
        ),
        migrations.AddField(
            model_name="examresult",
            name="original_result",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to original result if this is a retake",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retake_results",
                to="exam.examresult",
            ),
        ),
        migrations.AddField(
            model_name="examresult",
            name="retake_allowed_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when admin allowed retake", null=True
            ),
        ),
        migrations.AddField(
            model_name="examresult",
            name="retake_allowed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who allowed the retake",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retakes_allowed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="examresult",
            name="retake_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason why admin allowed retake (e.g., accidental submit)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="examresult",
            name="submission_status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("accidental_submit", "Accidental Submit"),
                    ("retake_allowed", "Retake Allowed"),
                    ("retaken", "Retaken"),
                ],
                default="submitted",
                help_text="Track submission status: accidental submit, retake allowed, etc.",
                max_length=20,
            ),
        ),
    ]
