# Generated by Django 5.1.2 on 2026-04-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_examresult_allow_retake_examresult_is_monitored_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledexam',
            name='allowed_tab_switches',
            field=models.PositiveIntegerField(default=3, help_text='Maximum tab switches allowed before auto-submit.'),
        ),
    ]
