# Generated by Django 5.1.2 on 2026-04-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_scheduledexam_allowed_tab_switches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledexam',
            name='section',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
