# Generated by Django 5.0.14 on 2026-04-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0018_convert_scheduledexam_datetimes_to_local"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examresult",
            name="submission_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("active", "Active"),
                    ("in_progress", "In Progress"),
                    ("suspicious", "Suspicious"),
                    ("submitted", "Submitted"),
                    ("accidental_submit", "Accidental Submit"),
                    ("retake_allowed", "Retake Allowed"),
                    ("retaken", "Retaken"),
                ],
                default="submitted",
                help_text="Track submission status: accidental submit, retake allowed, etc.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="examresult",
            name="current_question",
            field=models.IntegerField(
                default=1,
                help_text="Latest question number student is viewing during exam",
            ),
        ),
        migrations.AddField(
            model_name="examresult",
            name="last_active_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last heartbeat from student exam page",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="examresult",
            name="tab_switch_count",
            field=models.IntegerField(
                default=0,
                help_text="Number of tab switches detected during this exam attempt",
            ),
        ),
    ]
