# Generated by Django 5.1.2 on 2026-04-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_examresult_live_monitor_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='live_status',
            field=models.CharField(default='not_started', help_text='Realtime monitoring state from student heartbeat', max_length=30),
        ),
    ]
