# Generated by Django 5.1.2 on 2026-04-06 10:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0022_examquestion_section_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledexam',
            name='monitor_tpos',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'tpo'}, related_name='tpo_monitored_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledexam',
            name='monitor_trainers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'trainer'}, related_name='trainer_monitored_exams', to=settings.AUTH_USER_MODEL),
        ),
    ]
