# Generated by Django 5.1.2 on 2026-04-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0023_scheduledexam_monitor_tpos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledexam',
            name='monitor_tpos',
        ),
        migrations.RemoveField(
            model_name='scheduledexam',
            name='monitor_trainers',
        ),
        migrations.AddField(
            model_name='scheduledexam',
            name='live_exam_monitor',
            field=models.BooleanField(default=False, help_text='Enable live exam monitoring for trainers and TPO.'),
        ),
    ]
