# Generated by Django 5.1.2 on 2026-04-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0024_remove_scheduledexam_monitor_tpos_and_more'),
        ('tpo', '0001_initial'),
        ('trainer', '0011_alter_trainersessionreport_assignments_given_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledexam',
            name='monitor_tpos',
            field=models.ManyToManyField(blank=True, help_text='Select TPO who can monitor this exam.', related_name='monitored_exams', to='tpo.tpoprofile'),
        ),
        migrations.AddField(
            model_name='scheduledexam',
            name='monitor_trainers',
            field=models.ManyToManyField(blank=True, help_text='Select trainers who can monitor this exam.', related_name='monitored_exams', to='trainer.trainerprofile'),
        ),
    ]
