# Generated by Django 5.1.2 on 2026-07-22 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0025_scheduledexam_monitor_tpos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('status', models.CharField(default='Wrong Answer', help_text='Accepted, Wrong Answer, TLE, MLE, CE, RE, etc.', max_length=50)),
                ('runtime', models.FloatField(default=0.0, help_text='Total runtime in seconds')),
                ('memory', models.FloatField(default=0.0, help_text='Memory used in MB')),
                ('marks_obtained', models.FloatField(default=0.0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('exam_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_submissions', to='exam.examresult')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exam.examquestion')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit', models.FloatField(default=2.0, help_text='Time limit in seconds')),
                ('memory_limit', models.IntegerField(default=256, help_text='Memory limit in MB')),
                ('stack_size', models.IntegerField(default=64, help_text='Stack size in MB')),
                ('max_input_size', models.IntegerField(default=100000, help_text='Max input size in characters')),
                ('output_size', models.IntegerField(default=5, help_text='Max output size in MB')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='constraint', to='exam.examquestion')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_text', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='exam.examquestion')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='exam.examquestion')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(help_text='Standard input for the test case')),
                ('expected_output', models.TextField(help_text='Expected standard output')),
                ('is_public', models.BooleanField(default=False, help_text='Is it visible to the student (sample test case)?')),
                ('marks', models.FloatField(default=0.0, help_text='Marks assigned to this testcase')),
                ('weight', models.FloatField(default=1.0, help_text='Weight for score calculation')),
                ('time_limit_override', models.FloatField(blank=True, help_text='Override time limit in seconds', null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcase_details', to='exam.examquestion')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CodingTestCaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(help_text='PASS, FAIL, TLE, MLE, CE, RE', max_length=50)),
                ('runtime', models.FloatField(default=0.0)),
                ('memory', models.FloatField(default=0.0)),
                ('output', models.TextField(blank=True, help_text='Captured output (only stored for public/sample cases or errors)', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('marks_awarded', models.FloatField(default=0.0)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcase_results', to='exam.codingsubmission')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.questiontestcase')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('code', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='exam.examquestion')),
            ],
            options={
                'unique_together': {('question', 'language')},
            },
        ),
        migrations.CreateModel(
            name='QuestionStarterCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(help_text='e.g. python, java, cpp, c, csharp, javascript, php', max_length=50)),
                ('code', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starter_codes', to='exam.examquestion')),
            ],
            options={
                'unique_together': {('question', 'language')},
            },
        ),
    ]
