# Generated by Django 5.1.2 on 2026-07-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0026_codingsubmission_questionconstraint_questionhint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
