# Generated by Django 5.1.2 on 2026-07-22 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0028_questionversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingtestcaseresult',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='codingtestcaseresult',
            name='test_case',
        ),
        migrations.RemoveField(
            model_name='questionconstraint',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionhint',
            name='question',
        ),
        migrations.AlterUniqueTogether(
            name='questionsolution',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='questionsolution',
            name='question',
        ),
        migrations.AlterUniqueTogether(
            name='questionstartercode',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='questionstartercode',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questiontag',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questiontestcase',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionversion',
            name='author',
        ),
        migrations.RemoveField(
            model_name='questionversion',
            name='question',
        ),
        migrations.CreateModel(
            name='ExamCodingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_statement', models.TextField(blank=True, null=True)),
                ('input_format', models.TextField(blank=True, null=True)),
                ('output_format', models.TextField(blank=True, null=True)),
                ('constraints', models.TextField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('sample_input', models.TextField(blank=True, null=True)),
                ('sample_output', models.TextField(blank=True, null=True)),
                ('supported_languages', models.JSONField(blank=True, default=list)),
                ('boilerplate_code', models.JSONField(blank=True, default=dict)),
                ('time_limit_ms', models.IntegerField(default=1000)),
                ('memory_limit_mb', models.IntegerField(default=256)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], default='easy', max_length=15)),
                ('difficulty_score', models.IntegerField(default=2)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coding_details', to='exam.examquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ExamCodingTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('test_case_type', models.CharField(choices=[('sample', 'Sample'), ('evaluation', 'Evaluation'), ('hidden', 'Hidden')], default='hidden', max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('coding_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='exam.examcodingdetails')),
            ],
        ),
        migrations.DeleteModel(
            name='CodingSubmission',
        ),
        migrations.DeleteModel(
            name='CodingTestCaseResult',
        ),
        migrations.DeleteModel(
            name='QuestionConstraint',
        ),
        migrations.DeleteModel(
            name='QuestionHint',
        ),
        migrations.DeleteModel(
            name='QuestionSolution',
        ),
        migrations.DeleteModel(
            name='QuestionStarterCode',
        ),
        migrations.DeleteModel(
            name='QuestionTag',
        ),
        migrations.DeleteModel(
            name='QuestionTestCase',
        ),
        migrations.DeleteModel(
            name='QuestionVersion',
        ),
    ]
