# Generated by Django 5.1.2 on 2026-07-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0029_remove_codingtestcaseresult_submission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examcodingtestcase',
            name='coding_details',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='is_verified',
        ),
        migrations.DeleteModel(
            name='ExamCodingDetails',
        ),
        migrations.DeleteModel(
            name='ExamCodingTestCase',
        ),
    ]
