# Generated by Django 5.1.2 on 2026-07-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0030_remove_examcodingtestcase_coding_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='coding_duration_minutes',
            field=models.IntegerField(default=0, help_text='Duration for Coding section in minutes'),
        ),
        migrations.AddField(
            model_name='exam',
            name='mcq_duration_minutes',
            field=models.IntegerField(default=0, help_text='Duration for MCQ section in minutes'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='coding_started_at',
            field=models.DateTimeField(blank=True, help_text='When the student started the Coding section', null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='current_section',
            field=models.CharField(default='all', help_text="Active section: 'mcq', 'coding', or 'all'", max_length=20),
        ),
        migrations.AddField(
            model_name='examresult',
            name='mcq_started_at',
            field=models.DateTimeField(blank=True, help_text='When the student started the MCQ section', null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='mcq_submitted',
            field=models.BooleanField(default=False, help_text='True if student has submitted MCQ section'),
        ),
    ]
