# Generated by Django 5.1.2 on 2026-07-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0031_exam_coding_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='device_session_token',
            field=models.CharField(blank=True, help_text='Unique token to identify the active device session to prevent multiple logins taking the exam concurrently.', max_length=100, null=True),
        ),
    ]
