# Generated by Django 5.1.2 on 2026-08-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0032_examresult_device_session_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='submission_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('active', 'Active'), ('in_progress', 'In Progress'), ('suspicious', 'Suspicious'), ('submitted', 'Submitted'), ('accidental_submit', 'Accidental Submit'), ('retake_allowed', 'Retake Allowed'), ('retaken', 'Retaken')], db_index=True, default='submitted', help_text='Track submission status: accidental submit, retake allowed, etc.', max_length=20),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='scheduledexam',
            name='end_datetime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='scheduledexam',
            name='start_datetime',
            field=models.DateTimeField(db_index=True),
        ),
    ]
