# Generated by Django 5.1.2 on 2026-08-04 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0035_remove_examresult_evaluation_status_and_more'),
        ('pre_assessment', '0001_initial'),
        ('student', '0009_alter_studentprofile_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='pre_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='pre_assessment.preassessmentexam'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='submission_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('active', 'Active'), ('in_progress', 'In Progress'), ('suspicious', 'Suspicious'), ('submitted', 'Submitted'), ('accidental_submit', 'Accidental Submit'), ('retake_allowed', 'Retake Allowed'), ('retaken', 'Retaken')], default='submitted', help_text='Track submission status: accidental submit, retake allowed, etc.', max_length=20),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='scheduledexam',
            name='end_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='scheduledexam',
            name='start_datetime',
            field=models.DateTimeField(),
        ),
    ]
