# Generated by Django 5.1.2 on 2026-08-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0036_examresult_pre_assessment_alter_examresult_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='candidate_course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='candidate_sem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='candidate_usn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='candidate_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
