# Generated by Django 5.1.2 on 2026-08-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0037_examresult_candidate_course_examresult_candidate_sem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='candidate_college',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
