# Generated by Django 5.1.2 on 2026-08-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0038_examresult_candidate_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='selected_question_ids',
            field=models.JSONField(blank=True, help_text='List of question IDs assigned to this student for this attempt', null=True),
        ),
        migrations.AddField(
            model_name='scheduledexam',
            name='random_question_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of random questions to schedule for each student (leave blank for all questions).', null=True),
        ),
    ]
