# Generated by Django 5.1.2 on 2026-09-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0039_examresult_selected_question_ids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='selected_question_ids',
        ),
        migrations.RemoveField(
            model_name='scheduledexam',
            name='random_question_count',
        ),
    ]
