# Generated by Django 5.1.2 on 2026-09-16 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0040_remove_examresult_selected_question_ids_and_more"),
        ("pre_assessment", "0003_remove_preassessmentexam_college"),
        ("student", "0011_remove_studentprofile_resume_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="examresult",
            index=models.Index(
                fields=["student", "submission_status", "submitted_at"],
                name="exam_examre_student_9c732c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="examresult",
            index=models.Index(
                fields=["scheduled_exam", "student", "submitted_at"],
                name="exam_examre_schedul_cc8bbc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="examresult",
            index=models.Index(
                fields=["pre_assessment", "candidate_email", "submission_status"],
                name="exam_examre_pre_ass_061af2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="examresult",
            index=models.Index(
                fields=["pre_assessment", "candidate_usn", "submission_status"],
                name="exam_examre_pre_ass_0a960b_idx",
            ),
        ),
    ]
