# Generated by Django 5.1.2 on 2026-10-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0041_examresult_exam_examre_student_9c732c_idx_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='examresult',
                    name='exam_examre_student_9c732c_idx',
                ),
                migrations.RemoveIndex(
                    model_name='examresult',
                    name='exam_examre_schedul_cc8bbc_idx',
                ),
                migrations.RemoveIndex(
                    model_name='examresult',
                    name='exam_examre_pre_ass_061af2_idx',
                ),
                migrations.RemoveIndex(
                    model_name='examresult',
                    name='exam_examre_pre_ass_0a960b_idx',
                ),
                migrations.AddField(
                    model_name='exam',
                    name='questions_to_display',
                    field=models.PositiveIntegerField(default=0, help_text='Number of questions to display to each student (0 = all questions in pool)'),
                ),
                migrations.AddField(
                    model_name='examresult',
                    name='browser_name',
                    field=models.CharField(blank=True, help_text='Browser e.g. Chrome, Safari, Edge, Firefox', max_length=100, null=True),
                ),
                migrations.AddField(
                    model_name='examresult',
                    name='device_info',
                    field=models.CharField(blank=True, help_text="Human-readable device & OS description, e.g. 'Laptop (Windows 11 • Chrome)' or 'Mobile (Android • Chrome)'", max_length=255, null=True),
                ),
                migrations.AddField(
                    model_name='examresult',
                    name='device_type',
                    field=models.CharField(blank=True, help_text='Desktop/Laptop, Mobile, Tablet, etc.', max_length=50, null=True),
                ),
                migrations.AddField(
                    model_name='examresult',
                    name='ip_address',
                    field=models.CharField(blank=True, help_text='IP address of candidate', max_length=64, null=True),
                ),
                migrations.AddField(
                    model_name='examresult',
                    name='os_name',
                    field=models.CharField(blank=True, help_text='Operating system e.g. Android, iOS, Windows, macOS, Linux', max_length=100, null=True),
                ),
                migrations.AddField(
                    model_name='examresult',
                    name='selected_question_ids',
                    field=models.JSONField(blank=True, help_text='List of question IDs assigned to this student for this attempt', null=True),
                ),
                migrations.AddField(
                    model_name='examresult',
                    name='user_agent',
                    field=models.TextField(blank=True, help_text='Full user agent string', null=True),
                ),
                migrations.AddField(
                    model_name='scheduledexam',
                    name='random_question_count',
                    field=models.PositiveIntegerField(blank=True, help_text='Number of random questions to schedule for each student (leave blank to use exam setting)', null=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE "exam_exam" ADD COLUMN IF NOT EXISTS "questions_to_display" integer NOT NULL DEFAULT 0;
                    ALTER TABLE "exam_examresult" ADD COLUMN IF NOT EXISTS "browser_name" varchar(100) NULL;
                    ALTER TABLE "exam_examresult" ADD COLUMN IF NOT EXISTS "device_info" varchar(255) NULL;
                    ALTER TABLE "exam_examresult" ADD COLUMN IF NOT EXISTS "device_type" varchar(50) NULL;
                    ALTER TABLE "exam_examresult" ADD COLUMN IF NOT EXISTS "ip_address" varchar(64) NULL;
                    ALTER TABLE "exam_examresult" ADD COLUMN IF NOT EXISTS "os_name" varchar(100) NULL;
                    ALTER TABLE "exam_examresult" ADD COLUMN IF NOT EXISTS "selected_question_ids" jsonb NULL;
                    ALTER TABLE "exam_examresult" ADD COLUMN IF NOT EXISTS "user_agent" text NULL;
                    ALTER TABLE "exam_scheduledexam" ADD COLUMN IF NOT EXISTS "random_question_count" integer NULL;
                    DROP INDEX IF EXISTS "exam_examre_student_9c732c_idx";
                    DROP INDEX IF EXISTS "exam_examre_schedul_cc8bbc_idx";
                    DROP INDEX IF EXISTS "exam_examre_pre_ass_061af2_idx";
                    DROP INDEX IF EXISTS "exam_examre_pre_ass_0a960b_idx";
                    """,
                    reverse_sql="""
                    ALTER TABLE "exam_examresult" DROP COLUMN IF EXISTS "browser_name";
                    ALTER TABLE "exam_examresult" DROP COLUMN IF EXISTS "device_info";
                    ALTER TABLE "exam_examresult" DROP COLUMN IF EXISTS "device_type";
                    ALTER TABLE "exam_examresult" DROP COLUMN IF EXISTS "ip_address";
                    ALTER TABLE "exam_examresult" DROP COLUMN IF EXISTS "os_name";
                    ALTER TABLE "exam_examresult" DROP COLUMN IF EXISTS "selected_question_ids";
                    ALTER TABLE "exam_examresult" DROP COLUMN IF EXISTS "user_agent";
                    """
                )
            ]
        )
    ]
