# Generated by Django 5.1.2 on 2026-10-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0042_remove_examresult_exam_examre_student_9c732c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='candidate_custom_data',
            field=models.JSONField(blank=True, default=dict, help_text='Custom collected candidate registration data (e.g. CGPA, Gender, GitHub, etc.)'),
        ),
    ]
