# Generated by Django 5.0.14 on 2025-08-06 16:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompilerConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("theme", models.CharField(default="monokai", max_length=50)),
                ("font_size", models.IntegerField(default=14)),
                ("tab_size", models.IntegerField(default=4)),
                ("word_wrap", models.BooleanField(default=True)),
                ("line_numbers", models.BooleanField(default=True)),
                ("auto_save", models.BooleanField(default=True)),
                (
                    "default_optimization_level",
                    models.CharField(default="-O2", max_length=10),
                ),
                ("enable_warnings", models.BooleanField(default=True)),
                ("enable_debug_info", models.BooleanField(default=False)),
                ("auto_format_code", models.BooleanField(default=True)),
                ("execution_timeout", models.IntegerField(default=30)),
                ("memory_limit", models.IntegerField(default=256)),
                ("email_notifications", models.BooleanField(default=False)),
                ("browser_notifications", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compiler_config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "compiler_configurations",
            },
        ),
        migrations.CreateModel(
            name="CompilationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("c", "C"),
                            ("cpp", "C++"),
                            ("java", "Java"),
                            ("csharp", "C#"),
                            ("assembly", "Assembly"),
                            ("dotnet", ".NET"),
                            ("python", "Python"),
                            ("php", "PHP"),
                            ("html", "HTML"),
                            ("css", "CSS"),
                            ("javascript", "JavaScript"),
                            ("cobol", "COBOL"),
                            ("r", "R"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_code", models.TextField()),
                ("input_data", models.TextField(blank=True, null=True)),
                ("compiler_flags", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("output", models.TextField(blank=True, null=True)),
                ("error_output", models.TextField(blank=True, null=True)),
                ("execution_time", models.FloatField(blank=True, null=True)),
                ("memory_usage", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("client_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compilation_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "compiler_compilation_jobs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="compiler_co_user_id_b90da0_idx",
                    ),
                    models.Index(
                        fields=["status"], name="compiler_co_status_aaa33e_idx"
                    ),
                    models.Index(
                        fields=["language"], name="compiler_co_languag_6faa7b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CompilerStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("c", "C"),
                            ("cpp", "C++"),
                            ("java", "Java"),
                            ("csharp", "C#"),
                            ("assembly", "Assembly"),
                            ("dotnet", ".NET"),
                            ("python", "Python"),
                            ("php", "PHP"),
                            ("html", "HTML"),
                            ("css", "CSS"),
                            ("javascript", "JavaScript"),
                            ("cobol", "COBOL"),
                            ("r", "R"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_compilations", models.IntegerField(default=0)),
                ("successful_compilations", models.IntegerField(default=0)),
                ("failed_compilations", models.IntegerField(default=0)),
                ("total_execution_time", models.FloatField(default=0.0)),
                ("total_lines_of_code", models.IntegerField(default=0)),
                ("last_compilation_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compiler_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "compiler_statistics",
                "indexes": [
                    models.Index(
                        fields=["user", "language"],
                        name="compiler_st_user_id_70489b_idx",
                    ),
                    models.Index(
                        fields=["language"], name="compiler_st_languag_a52557_idx"
                    ),
                ],
                "unique_together": {("user", "language")},
            },
        ),
        migrations.CreateModel(
            name="CompilerTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("c", "C"),
                            ("cpp", "C++"),
                            ("java", "Java"),
                            ("csharp", "C#"),
                            ("assembly", "Assembly"),
                            ("dotnet", ".NET"),
                            ("python", "Python"),
                            ("php", "PHP"),
                            ("html", "HTML"),
                            ("css", "CSS"),
                            ("javascript", "JavaScript"),
                            ("cobol", "COBOL"),
                            ("r", "R"),
                        ],
                        max_length=20,
                    ),
                ),
                ("template_code", models.TextField()),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("shared", "Shared"),
                        ],
                        default="private",
                        max_length=10,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "compiler_templates",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["language", "-created_at"],
                        name="compiler_te_languag_deea5c_idx",
                    ),
                    models.Index(
                        fields=["visibility"], name="compiler_te_visibil_8e98a8_idx"
                    ),
                    models.Index(
                        fields=["author"], name="compiler_te_author__fe7f60_idx"
                    ),
                ],
            },
        ),
    ]
