# Generated by Django 5.0.14 on 2025-08-07 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compiler", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compilerconfiguration",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="compilerstatistics",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="compilerstatistics",
            name="user",
        ),
        migrations.RemoveField(
            model_name="compilertemplate",
            name="author",
        ),
        migrations.DeleteModel(
            name="CompilationJob",
        ),
        migrations.DeleteModel(
            name="CompilerConfiguration",
        ),
        migrations.DeleteModel(
            name="CompilerStatistics",
        ),
        migrations.DeleteModel(
            name="CompilerTemplate",
        ),
    ]
