"""
Django settings for atomm_lms project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import environ
import os
from csp.constants import NONCE
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Initialise environment variables
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# MEDIA CONFIGURATION — required for serving uploaded files (like exam question images)

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/
#Secret key for ITS_DANGEROUS which is used in token gengeration
#ITS_DANGEROUS_SECRET = env("ITS_DANGEROUS_SECRET")
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list(
    'ALLOWED_HOSTS',
    default=['127.0.0.1', 'localhost', '.ngrok-free.dev', '.ngrok.io', '.ngrok.app'],
)

CSRF_TRUSTED_ORIGINS = env.list(
    'CSRF_TRUSTED_ORIGINS',
    default=['https://*.ngrok-free.dev', 'https://*.ngrok.io', 'https://*.ngrok.app'],
)
# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users', 
    "admin_panel",
    'college',
    'material',
    'student',
    'tpo',
    'trainer',
    'exam',
    'practicetest',
    'csp',
    'company_prep',
    'pre_assessment',
]
#added AUTH_USER_MODEL to make django use 'users.User' 
AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "csp.middleware.CSPMiddleware",
    "atomm_lms.middleware.CSPFrameAllowMiddleware",
    "student.middleware.StudentAccessMiddleware",  # Block paused student groups
]

ROOT_URLCONF = 'atomm_lms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Project-level templates directory (optional)
        'APP_DIRS': True,  # Ensure this is True for app-level templates to work
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'atomm_lms.wsgi.application'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'student_dashboard'
LOGOUT_REDIRECT_URL = 'login'
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
        'CONN_MAX_AGE': env.int('DB_CONN_MAX_AGE', default=60),
        'CONN_HEALTH_CHECKS': True,
    }
}

REDIS_URL = env('REDIS_URL', default='')
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }
    SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'atomm-lms-local-cache',
        }
    }

RATELIMIT_FAIL_OPEN = env.bool('RATELIMIT_FAIL_OPEN', default=False)
LOGIN_IP_RATE = env('LOGIN_IP_RATE', default='100/10m')
LOGIN_EMAIL_RATE = env('LOGIN_EMAIL_RATE', default='10/10m')
PASSWORD_RESET_IP_RATE = env('PASSWORD_RESET_IP_RATE', default='10/h')
PASSWORD_RESET_EMAIL_RATE = env('PASSWORD_RESET_EMAIL_RATE', default='10/h')
COMPILER_RATE = env('COMPILER_RATE', default='10/m')
COMPILER_MAX_CONCURRENT = env.int('COMPILER_MAX_CONCURRENT', default=8)
COMPILER_RETRY_AFTER = env.int('COMPILER_RETRY_AFTER', default=5)
COMPILER_DOCKER_BINARY = env('COMPILER_DOCKER_BINARY', default='docker')
COMPILER_SANDBOX_IMAGE = env('COMPILER_SANDBOX_IMAGE', default='atomm-lms-compiler-sandbox:latest')
COMPILER_SANDBOX_MEMORY = env('COMPILER_SANDBOX_MEMORY', default='256m')
COMPILER_SANDBOX_CPUS = env('COMPILER_SANDBOX_CPUS', default='0.5')
COMPILER_SANDBOX_PIDS = env.int('COMPILER_SANDBOX_PIDS', default=64)
COMPILER_SANDBOX_WALL_TIMEOUT = env.int('COMPILER_SANDBOX_WALL_TIMEOUT', default=25)
COMPILER_OUTPUT_LIMIT = env.int('COMPILER_OUTPUT_LIMIT', default=262144)

CELERY_BROKER_URL = env('CELERY_BROKER_URL', default=REDIS_URL)
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default=REDIS_URL)
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_TIME_LIMIT = env.int('CELERY_TASK_TIME_LIMIT', default=40)
CELERY_TASK_SOFT_TIME_LIMIT = env.int('CELERY_TASK_SOFT_TIME_LIMIT', default=35)
CELERY_TASK_ROUTES = {
    'exam.compiler_tasks.execute_compiler_job': {'queue': 'compiler_queue'},
}
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

#STATIC_URL = 'static/'
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"  # Directory where static files will be collected

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#for development using default email
EMAIL_BACKEND = env(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend',
)
DEFAULT_FROM_EMAIL = 'webmaster@localhost'



SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_HSTS_SECONDS = 31536000   # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_REFERRER_POLICY = "same-origin"
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=not DEBUG)
SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=not DEBUG)

# Content Security Policy (add via SecurityMiddleware or with a plugin, or server headers)
# Example:
# CSP_DEFAULT_SRC = ("'self'",)

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")  # if behind a proxy/load balancer
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=not DEBUG)

#### CONTENT SECURITY POLICIES CSP  
CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": ("'self'",),
        "script-src": ("'self'", "https://cdnjs.cloudflare.com", "https://cdn.jsdelivr.net", "https://cdn.jsdelivr.net/npm", NONCE),
        "style-src": ("'self'", "https://fonts.googleapis.com", "https://cdnjs.cloudflare.com"),
        "font-src": ("'self'", "https://fonts.gstatic.com"),
        "img-src": ("'self'", "data:", "blob:", "https://s3.amazonaws.com", "https://*.amazonaws.com"),
        "connect-src": ("'self'", "https://s3.amazonaws.com", "https://*.amazonaws.com"),
        "object-src": ("'none'",),
        "base-uri": ("'self'",),
        "form-action": ("'self'",),
        "frame-ancestors": ("'none'",),}
}

#, "'unsafe-inline'"


# --------------------------------------------------------------------
#  Trainer PDF Upload Configuration — allows large resume uploads
# --------------------------------------------------------------------
# Django default = 2.5 MB → increased to 30 MB (30 × 1024 × 1024 bytes)
# Allow up to 60 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 62914560    # 60 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 62914560    # 60 MB

