# Generated by Django 5.1.2 on 2025-06-11 08:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college', '0001_initial'),
        ('material', '0002_alter_module_module_name'),
        ('trainer', '0003_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('slot_no', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')])),
                ('semester', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('done', models.BooleanField(default=False)),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.section')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.course')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.domain')),
                ('subdomain', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='material.subdomain')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainer.trainerprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('date', 'slot_no', 'Section', 'course', 'semester', 'college'), name='unique_session_schedule'), models.UniqueConstraint(fields=('date', 'slot_no', 'trainer'), name='unique_trainer_schedule')],
            },
        ),
    ]
