# Generated by Django 5.1.2 on 2025-06-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionschedule',
            name='reopened',
            field=models.BooleanField(default=False),
        ),
    ]
