# Generated by Django 5.1.2 on 2025-07-01 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_sessionschedule_reopened'),
        ('material', '0002_alter_module_module_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionschedule',
            name='reopened',
        ),
        migrations.AlterField(
            model_name='sessionschedule',
            name='subdomain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.subdomain'),
        ),
    ]
