# Generated by Django 5.1.2 on 2025-10-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_remove_sessionschedule_reopened_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionschedule',
            name='year',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], db_index=True, default=1),
            preserve_default=False,
        ),
    ]
