# Generated by Django 5.1.2 on 2025-11-04 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_sessionschedule_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionschedule',
            old_name='Section',
            new_name='section',
        ),
    ]
