# Generated by Django 5.1.2 on 2025-11-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_rename_section_sessionschedule_section'),
        ('college', '0002_alter_section_name'),
        ('material', '0003_material_document_file_material_excel_file_and_more'),
        ('trainer', '0011_alter_trainersessionreport_assignments_given_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sessionschedule',
            name='unique_session_schedule',
        ),
        migrations.AddConstraint(
            model_name='sessionschedule',
            constraint=models.UniqueConstraint(fields=('date', 'slot_no', 'section', 'course', 'semester', 'college'), name='unique_session_schedule'),
        ),
    ]
