# Generated by Django 5.1.2 on 2026-08-10 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_remove_sessionschedule_unique_session_schedule_and_more'),
        ('material', '0003_material_document_file_material_excel_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionschedule',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.module'),
        ),
    ]
