# Generated by Django 5.1.2 on 2025-10-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
