# Generated by Django 5.1.2 on 2026-07-23 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_alter_section_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroupAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('is_paused', models.BooleanField(default=False)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('paused_by', models.CharField(blank=True, max_length=150, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_access', to='college.college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.course')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.section')),
            ],
            options={
                'unique_together': {('college', 'year', 'semester', 'section', 'course')},
            },
        ),
    ]
