# Generated by Django 5.1.2 on 2026-07-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_student_group_access'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentgroupaccess',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentgroupaccess',
            name='batch_year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterUniqueTogether(
            name='studentgroupaccess',
            unique_together={('college', 'year', 'semester', 'section', 'course', 'batch_year')},
        ),
    ]
