# Generated by Django 5.1.2 on 2026-07-28 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_batch_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_courses', to='college.college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_courses', to='college.course')),
            ],
            options={
                'unique_together': {('college', 'course')},
            },
        ),
        migrations.CreateModel(
            name='CollegeCourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='college.collegecourse')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_course_sections', to='college.section')),
            ],
            options={
                'unique_together': {('college_course', 'section')},
            },
        ),
    ]
