# Generated by Django 5.1.2 on 2025-05-27 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0002_alter_module_module_name'),
        ('users', '0004_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'role': 'trainer'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('skills', models.CharField(max_length=100)),
                ('profile_pdf', models.FileField(blank=True, null=True, upload_to='trainer_profiles/pdfs/')),
                ('domains', models.ManyToManyField(to='material.domain')),
                ('subdomains', models.ManyToManyField(blank=True, to='material.subdomain')),
            ],
        ),
    ]
