# Generated by Django 5.1.2 on 2025-05-29 16:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_alter_module_module_name'),
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainerprofile',
            old_name='skills',
            new_name='skill_summary',
        ),
        migrations.RemoveField(
            model_name='trainerprofile',
            name='domains',
        ),
        migrations.RemoveField(
            model_name='trainerprofile',
            name='subdomains',
        ),
        migrations.CreateModel(
            name='TrainerSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.domain')),
                ('subdomain', models.ForeignKey(blank=True, help_text='Leave blank if this is a domain-only skill', null=True, on_delete=django.db.models.deletion.CASCADE, to='material.subdomain')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_skills', to='trainer.trainerprofile')),
            ],
            options={
                'verbose_name': 'Trainer Skill',
                'verbose_name_plural': 'Trainer Skills',
                'unique_together': {('trainer', 'domain', 'subdomain')},
            },
        ),
    ]
