# Generated by Django 5.1.2 on 2025-06-21 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
        ('material', '0002_alter_module_module_name'),
        ('trainer', '0004_attendancerecord_delete_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerSessionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('semester', models.IntegerField()),
                ('branch', models.CharField(max_length=100)),
                ('other_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('module', models.CharField(max_length=200)),
                ('total_students', models.PositiveIntegerField()),
                ('present_students', models.PositiveIntegerField()),
                ('absent_students', models.PositiveIntegerField()),
                ('exercises_solved', models.PositiveIntegerField(blank=True, null=True)),
                ('materials_shared', models.CharField(max_length=10)),
                ('assignments_given', models.CharField(max_length=10)),
                ('best_performer', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.course')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.domain')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.trainerprofile')),
            ],
        ),
    ]
