# Generated by Django 5.1.2 on 2025-06-30 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_alter_module_module_name'),
        ('trainer', '0005_trainersessionreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerskill',
            name='subdomain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.subdomain'),
        ),
    ]
