# Generated by Django 5.1.2 on 2025-10-21 08:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_remove_sessionschedule_reopened_and_more'),
        ('college', '0002_alter_section_name'),
        ('material', '0003_material_document_file_material_excel_file_and_more'),
        ('trainer', '0006_alter_trainerskill_subdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerDailyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('semester', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], db_index=True)),
                ('module', models.CharField(max_length=200)),
                ('total_students', models.PositiveIntegerField()),
                ('present_students', models.PositiveIntegerField()),
                ('absent_students', models.PositiveIntegerField()),
                ('exercises_solved', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('materials_shared', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('assignments_given', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('best_performer', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.TextField(max_length=2000)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.course')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.domain')),
                ('session', models.ForeignKey(blank=True, help_text='Optional: link this report to a scheduled session.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.sessionschedule')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='trainer.trainerprofile')),
            ],
            options={
                'verbose_name': 'Trainer Daily Report',
                'verbose_name_plural': 'Trainer Daily Reports',
                'ordering': ['-date'],
                'unique_together': {('trainer', 'date')},
            },
        ),
    ]
