# Generated by Django 5.1.2 on 2025-10-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0007_trainerdailyreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainerDailyReport',
        ),
    ]
