# Generated by Django 5.1.2 on 2025-10-28 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_alter_section_name'),
        ('material', '0003_material_document_file_material_excel_file_and_more'),
        ('trainer', '0008_delete_trainerdailyreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainersessionreport',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='trainersessionreport',
            name='other_branch',
        ),
        migrations.AddField(
            model_name='trainersessionreport',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college.section'),
        ),
        migrations.AddField(
            model_name='trainersessionreport',
            name='subdomain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.subdomain'),
        ),
        migrations.AddField(
            model_name='trainersessionreport',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
