# Generated by Django 5.1.2 on 2025-10-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0009_remove_trainersessionreport_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainersessionreport',
            name='exercises_solved',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
