# Generated by Django 5.1.2 on 2025-10-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0010_alter_trainersessionreport_exercises_solved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainersessionreport',
            name='assignments_given',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='trainersessionreport',
            name='exercises_solved',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='trainersessionreport',
            name='materials_shared',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
    ]
