# Generated by Django 5.1.2 on 2025-06-03 16:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college', '0001_initial'),
        ('material', '0002_alter_module_module_name'),
        ('student', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('passing_marks', models.FloatField()),
                ('max_marks', models.FloatField()),
                ('duration_minutes', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.domain')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_title', models.CharField(max_length=255)),
                ('total_marks', models.FloatField()),
                ('marks_obtained', models.FloatField()),
                ('attempted_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('wrong_answers', models.IntegerField(default=0)),
                ('question_wise_breakdown', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile')),
                ('practice_test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='practicetest.practicetest')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('type', models.CharField(choices=[('MCQ', 'MCQ'), ('TF', 'TrueFalse'), ('DESC', 'Descriptive')], max_length=10)),
                ('marks', models.FloatField()),
                ('negative_mark', models.FloatField(default=0)),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_keywords', models.JSONField(blank=True, null=True)),
                ('min_characters', models.IntegerField(blank=True, null=True)),
                ('practice_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicetest.practicetest')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledPracticeTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semester', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], db_index=True)),
                ('year', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], db_index=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.course')),
                ('practice_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='practicetest.practicetest')),
            ],
            options={
                'unique_together': {('practice_test', 'college', 'course', 'semester', 'year')},
            },
        ),
    ]
