# Generated by Django 5.1.2 on 2025-11-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicetest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicequestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='practice_questions/'),
        ),
        migrations.AlterField(
            model_name='practicequestion',
            name='type',
            field=models.CharField(choices=[('MCQ', 'MCQ'), ('TF', 'TrueFalse'), ('DESC', 'Descriptive'), ('CODE', 'Coding')], max_length=10),
        ),
    ]
