# Generated by Django 5.2.1 on 2025-11-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicetest', '0003_practiceresult_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicequestion',
            name='expected_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practicequestion',
            name='input_example',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practicequestion',
            name='test_cases',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
