# Generated by Django 5.1.2 on 2026-08-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicetest', '0004_practicequestion_expected_output_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceresult',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='scheduledpracticetest',
            name='end_datetime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='scheduledpracticetest',
            name='start_datetime',
            field=models.DateTimeField(db_index=True),
        ),
    ]
