# Generated by Django 5.1.2 on 2026-09-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practicetest", "0007_remove_practiceresult_evaluation_status_and_more"),
        ("student", "0011_remove_studentprofile_resume_data"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="practiceresult",
            index=models.Index(
                fields=["student", "submitted_at"],
                name="practicetes_student_ea6969_idx",
            ),
        ),
    ]
