# Generated by Django 5.1.2 on 2026-08-04 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_collegecourse_collegecoursesection'),
        ('pre_assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preassessmentexam',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_assessments', to='college.college'),
        ),
    ]
