# Generated by Django 5.1.2 on 2026-08-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_assessment', '0002_preassessmentexam_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preassessmentexam',
            name='college',
        ),
    ]
