# Generated by Django 5.1.2 on 2026-10-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_assessment', '0003_remove_preassessmentexam_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='preassessmentexam',
            name='allowed_tab_switches',
            field=models.PositiveIntegerField(default=3, help_text='Maximum allowed tab switches before auto-submit'),
        ),
        migrations.AddField(
            model_name='preassessmentexam',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='Assessment end date and time', null=True),
        ),
        migrations.AddField(
            model_name='preassessmentexam',
            name='start_datetime',
            field=models.DateTimeField(blank=True, help_text='Assessment start date and time', null=True),
        ),
    ]
