# Generated by Django 5.1.2 on 2026-10-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_assessment', '0004_preassessmentexam_allowed_tab_switches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preassessmentexam',
            name='registration_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Custom candidate registration form fields configuration'),
        ),
    ]
