# Generated by Django 5.1.2 on 2025-05-27 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college', '0001_initial'),
        ('users', '0004_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='TpoProfile',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'role': 'tpo'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.college')),
            ],
        ),
    ]
