# Generated by Django 5.1.2 on 2026-07-16 06:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0007_studentfeedback_sessiontrainerfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('package', models.CharField(max_length=50)),
                ('eligibility', models.TextField()),
                ('job_role', models.CharField(max_length=150)),
                ('selection_process', models.TextField()),
                ('expected_interview_date', models.DateField()),
                ('skills_required', models.JSONField(default=list)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='AIInterviewAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.IntegerField(default=0)),
                ('confidence', models.IntegerField(default=0)),
                ('communication', models.IntegerField(default=0)),
                ('eye_contact', models.IntegerField(default=0)),
                ('grammar', models.IntegerField(default=0)),
                ('recommendation', models.CharField(max_length=150)),
                ('feedback_details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_prep.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAptitudeQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(choices=[('Quantitative Aptitude', 'Quantitative Aptitude'), ('Logical Reasoning', 'Logical Reasoning'), ('Verbal Ability', 'Verbal Ability'), ('Data Interpretation', 'Data Interpretation')], max_length=100)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20)),
                ('question_text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aptitude_questions', to='company_prep.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyTechnicalQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil'), ('MBA', 'MBA')], max_length=20)),
                ('topic', models.CharField(max_length=100)),
                ('question_text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technical_questions', to='company_prep.company')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPrepAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_type', models.CharField(choices=[('Aptitude', 'Aptitude'), ('Technical', 'Technical')], max_length=20)),
                ('score', models.IntegerField()),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_prep.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCompanyProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_progress', models.IntegerField(default=0)),
                ('resume_match', models.IntegerField(default=0)),
                ('placement_readiness', models.IntegerField(default=0)),
                ('aptitude_score', models.IntegerField(default=0)),
                ('technical_score', models.IntegerField(default=0)),
                ('communication_score', models.IntegerField(default=0)),
                ('mock_interview_score', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_prep.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_progress', to='student.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'company')},
            },
        ),
    ]
