# Generated by Django 5.1.2 on 2026-07-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_prep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytechnicalquestion',
            name='type',
            field=models.CharField(choices=[('MCQ', 'MCQ'), ('Code', 'Code')], default='MCQ', max_length=10),
        ),
        migrations.AlterField(
            model_name='companytechnicalquestion',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companytechnicalquestion',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
