# Generated by Django 5.1.2 on 2026-07-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_prep', '0002_companytechnicalquestion_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='hr_interview_required',
            field=models.BooleanField(default=True, help_text='Specify if Round 3 (AI Video Interview) is required for this company'),
        ),
    ]
