# Generated by Django 5.1.2 on 2026-07-16 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_prep', '0003_company_hr_interview_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='eligibility',
        ),
        migrations.RemoveField(
            model_name='company',
            name='logo_url',
        ),
    ]
