# Generated by Django 5.1.2 on 2026-07-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_prep', '0004_remove_company_eligibility_remove_company_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='previous_papers',
            field=models.FileField(blank=True, help_text='Upload previous year question papers for students to download', null=True, upload_to='company_papers/'),
        ),
        migrations.AddField(
            model_name='company',
            name='technical_round_format',
            field=models.CharField(choices=[('MCQ', 'MCQ Only'), ('Compiler', 'Compiler Sandbox Only')], default='MCQ', help_text='Select format for Round 2 Technical Assessment', max_length=20),
        ),
    ]
