# Generated by Django 5.1.2 on 2026-07-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_prep', '0005_company_previous_papers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='company',
            name='hr_interview_required',
            field=models.BooleanField(default=False, help_text='Specify if Round 3 (AI Video Interview) is required for this company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
