# Generated by Django 5.1.2 on 2026-07-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_prep', '0006_company_year_alter_company_hr_interview_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload Company Logo', null=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='expected_interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='job_role',
            field=models.CharField(blank=True, default='General', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='package',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='selection_process',
            field=models.TextField(blank=True, default='Round 1: Aptitude -> Round 2: Technical & Coding', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='skills_required',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='company',
            name='year',
            field=models.IntegerField(blank=True, default=2024, null=True),
        ),
    ]
