# Generated by Django 5.1.2 on 2026-07-20 08:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_prep', '0007_company_logo_alter_company_expected_interview_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyQuestionPaper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(default=2024)),
                ('paper_file', models.FileField(blank=True, help_text='Upload question paper file', null=True, upload_to='company_papers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_papers', to='company_prep.company')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
