# Generated by Django 5.1.2 on 2026-07-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_prep', '0008_companyquestionpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyquestionpaper',
            name='selection_process',
            field=models.TextField(blank=True, default='Round 1: Aptitude -> Round 2: Technical & Coding', null=True),
        ),
        migrations.AddField(
            model_name='companyquestionpaper',
            name='technical_round_format',
            field=models.CharField(choices=[('MCQ', 'MCQ Only'), ('Compiler', 'Compiler Sandbox Only')], default='MCQ', max_length=20),
        ),
    ]
