# Generated by Django 5.1.2 on 2026-07-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_prep', '0009_companyquestionpaper_selection_process_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='test_duration_minutes',
            field=models.IntegerField(default=15, help_text='Test duration in minutes for company exams'),
        ),
    ]
