# Generated by Django 5.1.2 on 2026-08-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_prep', '0010_company_test_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaptitudequestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='company_questions/'),
        ),
        migrations.AddField(
            model_name='companyaptitudequestion',
            name='type',
            field=models.CharField(choices=[('MCQ', 'MCQ'), ('TF', 'TrueFalse')], default='MCQ', max_length=10),
        ),
        migrations.AddField(
            model_name='companytechnicalquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='company_questions/'),
        ),
        migrations.AlterField(
            model_name='companytechnicalquestion',
            name='type',
            field=models.CharField(choices=[('MCQ', 'MCQ'), ('Code', 'Code'), ('TF', 'TrueFalse')], default='MCQ', max_length=10),
        ),
    ]
