# Generated by Django 5.1.2 on 2026-08-04 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_collegecourse_collegecoursesection'),
        ('company_prep', '0011_companyaptitudequestion_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_preps', to='college.college'),
        ),
        migrations.AddField(
            model_name='company',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
