# Generated by Django 5.1.2 on 2026-08-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_prep', '0012_company_college_company_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytechnicalquestion',
            name='expected_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companytechnicalquestion',
            name='input_example',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companytechnicalquestion',
            name='test_cases',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
