# Generated by Django 5.1.2 on 2026-08-06 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_collegecourse_collegecoursesection'),
        ('company_prep', '0013_companytechnicalquestion_expected_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_preps_course', to='college.course'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='max_attempts',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='company',
            name='negative_marking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='round1_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='round1_duration',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='company',
            name='round1_name',
            field=models.CharField(default='Quantitative, Logical & Verbal Aptitude', max_length=150),
        ),
        migrations.AddField(
            model_name='company',
            name='round1_passing_pct',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='company',
            name='round1_questions',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='company',
            name='round2_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='round2_duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='company',
            name='round2_name',
            field=models.CharField(default='Technical Assessment', max_length=150),
        ),
        migrations.AddField(
            model_name='company',
            name='round2_questions',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='company',
            name='round2_technical_format',
            field=models.CharField(choices=[('MCQ', 'MCQ Only'), ('Coding', 'Coding Only'), ('MCQ_Coding', 'MCQ + Coding')], default='MCQ', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_preps_section', to='college.section'),
        ),
        migrations.AddField(
            model_name='company',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='shuffle_options',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='shuffle_questions',
            field=models.BooleanField(default=False),
        ),
    ]
