# Generated by Django 5.1.2 on 2026-08-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_prep', '0014_company_course_company_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='round2_passing_pct',
            field=models.IntegerField(default=60),
        ),
    ]
