# Generated by Django 5.1.2 on 2026-08-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_prep', '0015_company_round2_passing_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='place',
            field=models.CharField(blank=True, default='N/A', max_length=150, null=True),
        ),
    ]
