# Generated by Django 5.1.2 on 2025-09-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_alter_module_module_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='materials/docs/'),
        ),
        migrations.AddField(
            model_name='material',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='materials/sheets/'),
        ),
        migrations.AddField(
            model_name='material',
            name='ppt_file',
            field=models.FileField(blank=True, null=True, upload_to='materials/ppts/'),
        ),
    ]
