# Generated by Django 5.1.2 on 2025-06-14 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
