# Generated by Django 5.1.2 on 2025-06-21 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_delete_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
