# Generated by Django 5.1.2 on 2025-07-01 13:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_sessionschedule_reopened'),
        ('student', '0006_delete_attendance'),
        ('trainer', '0006_alter_trainerskill_subdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('content_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('session_engagement', models.CharField(choices=[('Very engaging and interactive', 'Very engaging and interactive'), ('Somewhat engaging', 'Somewhat engaging'), ('Neutral', 'Neutral'), ('Boring and unengaging', 'Boring and unengaging')], max_length=40)),
                ('future_interest', models.CharField(choices=[('Yes, definitely', 'Yes, definitely'), ('Yes, possibly', 'Yes, possibly'), ('Maybe', 'Maybe'), ('No', 'No')], max_length=20)),
                ('objectives_clarity', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('structure_logic', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('satisfaction', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('takeaways', models.TextField(max_length=1000)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SessionTrainerFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pace_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('knowledge_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('participation', models.CharField(choices=[('Always', 'Always'), ('Often', 'Often'), ('Rarely', 'Rarely'), ('Never', 'Never')], max_length=10)),
                ('examples', models.CharField(choices=[('Very Clear and Practical', 'Very Clear and Practical'), ('Somewhat Clear', 'Somewhat Clear'), ('Confusing at times', 'Confusing at times'), ('Not clear', 'Not clear')], max_length=30)),
                ('queries_rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.sessionschedule')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.trainerprofile')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_feedbacks', to='student.studentfeedback')),
            ],
            options={
                'unique_together': {('feedback', 'session', 'trainer')},
            },
        ),
    ]
