# Generated by Django 5.1.2 on 2026-07-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_studentfeedback_sessiontrainerfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='batch_year',
            field=models.IntegerField(db_index=True, default=2026, help_text='Academic intake year (e.g. 2024, 2025). Used to separate batches for pause/resume.'),
        ),
    ]
