# Generated by Django 5.1.2 on 2026-08-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_studentprofile_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='resume_data',
            field=models.TextField(blank=True, help_text='JSON representation of structured resume draft', null=True),
        ),
    ]
