# Generated by Django 5.1.2 on 2026-08-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_studentprofile_resume_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='resume_data',
        ),
    ]
