# Generated by Django 5.1.2 on 2026-08-02 17:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0034_examresult_evaluation_status'),
        ('practicetest', '0006_practiceresult_evaluation_status'),
        ('student', '0009_alter_studentprofile_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='Running', max_length=50)),
                ('jobs_processed', models.PositiveIntegerField(default=0)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('cpu', models.FloatField(default=0.0)),
                ('memory', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='CompilerJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(db_index=True, max_length=255)),
                ('question_id_fallback', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('language', models.CharField(max_length=50)),
                ('code', models.TextField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('timeout', 'Timeout')], db_index=True, default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('queue_wait_time', models.FloatField(blank=True, help_text='Wait time in queue in seconds', null=True)),
                ('execution_time', models.FloatField(blank=True, help_text='Compiler execution duration in seconds', null=True)),
                ('cpu_time', models.FloatField(blank=True, help_text='CPU time consumed in seconds', null=True)),
                ('memory_used', models.FloatField(blank=True, help_text='Memory consumed in MB', null=True)),
                ('stdout', models.TextField(blank=True, null=True)),
                ('stderr', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.exam')),
                ('exam_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.examquestion')),
                ('practice_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='practicetest.practicequestion')),
                ('practice_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='practicetest.practicetest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentprofile')),
            ],
        ),
    ]
